image: node:17-alpine3.14

stages:
  - deploy

deploy-lambda:
  only:
    - master
  stage: deploy
  before_script:
    - apk add --no-cache python3 py3-pip
    - npm config set prefix /usr/local
    - npm install -g serverless
  script:
    - sls plugin install -n serverless-domain-manager
    - sls plugin install -n serverless-python-requirements
    - sls deploy --verbose --conceal
