service: lib-lambda

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1
  stackName: lib-lambda-dev
  memorySize: 512
  timeout: 10
  deploymentBucket:
    blockPublicAccess: true
    name: ${ssm:/BUCKET_NAME}
  deploymentPrefix: serverless
  apiGateway:
    metrics: false
    apiKeySourceType: HEADER
    apiKeys:
      - name: myApiKey
        value: ${ssm:/API_KEY_SERVERLESS}
        description: Api key required for call functions

plugins:
  - serverless-domain-manager
  - serverless-python-requirements

custom:
  customDomain:
    domainName: ${ssm:/DOMAIN_NAME}
    certificateName: ${ssm:/CERTIFICATE_NAME}
    createRoute53Record: true
  pythonRequirements:
    dockerizePip: non-linux

functions:
  hello:
    name: hello
    handler: src/hello/hello.lambda_handler
    events:
      - http:
          path: /hello
          method: get
          cors:
            origin: '*'
            headers:
              - X-Api-Key
          private: true
      - schedule:
          name: hello-event
          rate: cron(30 18 ? * MON-SUN *)
